num1= int(input("Introduzca el primer numero "))
num2= int(input("introduzca el segundo numero "))
resta= (num1-num2)
distancia= abs(resta)
print ("la distancia entre ambos numeros es: " + str(distancia))